### ISSUE TITLE
Unable to call public APIs with httpRequest method in the SDK

### ISSUE THREAD

**Issue by ayshsandu** [asgardeo/asgardeo-auth-react-sdk#165]
**Describe the issue:**
Getting an error when trying to use httpRequest method from the SDK to call an API which doesn't require any authentication.

**How to reproduce:**
Call a public API endpoint with the above method
https://github.com/ayshsandu/readers-guild/blob/main/src/components/BookList.js#L35-L38

**Expected behavior:**
SDK should be able to invoke public APIs as well as secured ones. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
It appears that this issue is no longer reproducible in the latest SDK version. I just tried using the httpRequest method to interact with the public cat facts API and didn't face any errors[1].

Therefore, I am closing this issue. Please feel free to reopen it if you still encounter the same issue in the SDK v4 (latest version atm) and onwards.

[1] https://github.com/pavinduLakshan/cat-facts-demo/blob/master/src/pages/home.tsx#L101-L113
