### ISSUE TITLE
ReferenceError: origin is not defined on Nextjs 14

### ISSUE THREAD

**Issue by minhtuan412** [asgardeo/asgardeo-auth-react-sdk#217]
**Describe the issue:**
When i install and setup library in Nextjs 14 using App Routing follow document guide
I get error after run:
![Screenshot_2024-03-12-16-43-38-321_com signet messenger](https://github.com/asgardeo/asgardeo-auth-react-sdk/assets/99988937/c0e7c3ec-7ffb-43e0-9f30-e0ee03818aba)

In file layout.tsx
![Screenshot_2024-03-12-16-43-43-538_com signet messenger](https://github.com/asgardeo/asgardeo-auth-react-sdk/assets/99988937/e5b008ba-fcea-40f9-a68a-9fa2c3dcf019)

In file config.json
![Screenshot_2024-03-12-16-43-46-530_com signet messenger](https://github.com/asgardeo/asgardeo-auth-react-sdk/assets/99988937/888517a7-c4e7-43fe-9cd8-c9921f718afb)

Package.json
@asgardeo/@auth-react: 4.0.2
React, react-dom: 18
react-router-dom: 6.22.3
next: 14.1.3

**How to reproduce:**
npm run dev -> display error

**Expected behavior:**
Not display error, run and build success

**Environment information** 
 - Product Version: 
 - OS: Mac
 - Database:
 - Userstore:

**Comment by brionmario** [comment]
Hi @minhtuan412,

Thanks for reporting this issue.

`@asgardeo/auth-react` is actually meant to be used with client-side React contexts.
Since `NextJS` is a server side framework, the SDK would not work out of the box.
From the stacktrace, it looks to me like the SDK is trying to access a browser API (ex: window.location.origin) and failing since window is not available on the server. 

Until we rollout our own `nextjs` SDK, I would like to suggest `NextAuth`(https://next-auth.js.org/) which is an established SDK in the NextJS ecosystem and Asgardeo can be easily integrated with NextAuth.

You can have a look at the following two blogs written by @DonOmalVindula to get started:
- https://medium.com/@omalwijegunawardana/authenticate-next-js-applications-with-asgardeo-part-1-eb02fbcf7fb9?source=user_profile---------1----------------------------
-  https://medium.com/@omalwijegunawardana/authenticate-next-js-applications-with-asgardeo-part-2-2db5a45ebcb7?source=user_profile---------0----------------------------
