### ISSUE TITLE
App doesn't work when Block third-party cookies enabled

### ISSUE THREAD

**Issue by GDRDABARERA** [asgardeo/asgardeo-auth-react-sdk#43]
As latest browsers are blocking third party cookies, its good to create the single page app to compatible with that. If not when a person try this app for the first time in an incognito without knowing this will frustrate as the sample is not working

![image](https://user-images.githubusercontent.com/9637873/131356784-f61b2058-0af7-4171-a5b1-c810dd553d98.png)

**Comment by brionmario** [comment]
This was happening due to the usage of RP iframe for session management. We were enabling it by default.
To overcome the issue, we sent a PR disabling the iframe by default. https://github.com/asgardeo/asgardeo-auth-react-sdk/pull/38

@GDRDABARERA Could you please try with the latest sample and see if the issue is there?
